apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-test
  project: default
  source:
    chart: prometheus-blackbox-exporter
    helm:
      values: |
        {{ .Files.Get "blackbox-values.yaml" | nindent 8 }}
    repoURL: https://charts.helm.sh/stable
    targetRevision: 4.3.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
